name: myenv
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - asttokens=3.0.0=py313h06a4308_0
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.9.9=h06a4308_0
  - comm=0.2.1=py313h06a4308_0
  - debugpy=1.8.16=py313hbdd6827_0
  - decorator=5.2.1=py313h06a4308_0
  - executing=2.2.1=py313h06a4308_0
  - expat=2.7.1=h6a678d5_0
  - ipykernel=6.30.1=py313h06a4308_0
  - ipython=9.5.0=py313h06a4308_0
  - ipython_pygments_lexers=1.1.1=py313h06a4308_0
  - jedi=0.19.2=py313h06a4308_0
  - jupyter_client=8.6.3=py313h06a4308_0
  - jupyter_core=5.8.1=py313h06a4308_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libmpdec=4.0.0=h5eee18b_0
  - libsodium=1.0.20=heac8642_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - matplotlib-inline=0.1.7=py313h06a4308_0
  - ncurses=6.5=h7934f7d_0
  - nest-asyncio=1.6.0=py313h06a4308_0
  - openssl=3.0.18=hd6dcaed_0
  - packaging=25.0=py313h06a4308_0
  - parso=0.8.4=py313h06a4308_0
  - pexpect=4.9.0=py313h06a4308_0
  - pip=25.2=pyhc872135_0
  - platformdirs=4.3.7=py313h06a4308_0
  - prompt-toolkit=3.0.43=py313h06a4308_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - psutil=7.0.0=py313hee96239_0
  - pthread-stubs=0.3=h0ce48e5_1
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.3=py313h06a4308_0
  - pygments=2.19.1=py313h06a4308_0
  - python=3.13.7=h7e8bc2b_100_cp313
  - python-dateutil=2.9.0post0=py313h06a4308_2
  - python_abi=3.13=1_cp313
  - pyzmq=27.1.0=py313hcf8288c_0
  - readline=8.3=hc2a1206_0
  - setuptools=78.1.1=py313h06a4308_0
  - six=1.17.0=py313h06a4308_0
  - sqlite=3.50.2=hb25bd0a_1
  - stack_data=0.6.3=py313h06a4308_0
  - tk=8.6.15=h54e0aa7_0
  - tornado=6.5.1=py313h5eee18b_0
  - traitlets=5.14.3=py313h06a4308_0
  - tzdata=2025b=h04d1e81_0
  - wcwidth=0.2.13=py313h06a4308_0
  - wheel=0.45.1=py313h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zeromq=4.3.5=hb0a5e54_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
    - ale-py==0.11.2
    - attrs==25.4.0
    - bayesian-optimization==3.1.0
    - certifi==2025.11.12
    - charset-normalizer==3.4.4
    - click==8.3.1
    - cloudpickle==3.1.1
    - colorama==0.4.6
    - contourpy==1.3.3
    - cycler==0.12.1
    - farama-notifications==0.0.4
    - filelock==3.13.1
    - fonttools==4.60.1
    - fsspec==2024.6.1
    - gymnasium==1.2.1
    - idna==3.11
    - jinja2==3.1.4
    - joblib==1.5.2
    - jsonschema==4.25.1
    - jsonschema-specifications==2025.9.1
    - kiwisolver==1.4.9
    - markupsafe==3.0.2
    - matplotlib==3.10.7
    - mpmath==1.3.0
    - msgpack==1.1.2
    - networkx==3.3
    - numpy==2.3.5
    - nvidia-cublas-cu12==12.6.4.1
    - nvidia-cuda-cupti-cu12==12.6.80
    - nvidia-cuda-nvrtc-cu12==12.6.77
    - nvidia-cuda-runtime-cu12==12.6.77
    - nvidia-cudnn-cu12==9.10.2.21
    - nvidia-cufft-cu12==11.3.0.4
    - nvidia-cufile-cu12==1.11.1.6
    - nvidia-curand-cu12==10.3.7.77
    - nvidia-cusolver-cu12==11.7.1.2
    - nvidia-cusparse-cu12==12.5.4.2
    - nvidia-cusparselt-cu12==0.7.1
    - nvidia-nccl-cu12==2.27.3
    - nvidia-nvjitlink-cu12==12.6.85
    - nvidia-nvtx-cu12==12.6.77
    - pillow==11.0.0
    - protobuf==6.33.1
    - pygame==2.6.1
    - pyparsing==3.2.5
    - pyyaml==6.0.3
    - ray==2.51.1
    - referencing==0.37.0
    - requests==2.32.5
    - rpds-py==0.29.0
    - scikit-learn==1.7.2
    - scipy==1.16.3
    - sympy==1.13.3
    - threadpoolctl==3.6.0
    - torch==2.8.0+cu126
    - torchvision==0.23.0+cu126
    - triton==3.4.0
    - typing-extensions==4.12.2
    - urllib3==2.5.0
prefix: /nfs/home/ptn8247/.conda/envs/myenv
